plugins {
    id 'com.android.application'
}

android {
    namespace 'com.starcommunication.isp'
    compileSdk 35

    defaultConfig {
        applicationId 'com.starcommunication.isp'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
