from pathlib import Path
p=Path("app/src/main/assets/index.html")
s=p.read_text()
old_start=s.index("function loginScreen()")
old_end=s.index("function startup()",old_start)
new=r"""function accountCard(title,sub){return '<div style="padding:26px 16px 100px"><div class="section" style="margin-top:25px;padding:22px"><div style="text-align:center"><img src="logo.svg" style="width:72px;height:72px;border-radius:18px"><h1 style="margin:12px 0 3px;color:#0b2145">STAR COMMUNICATION</h1><div class="muted">'+esc(sub)+'</div></div><h3 style="margin-top:22px">'+esc(title)+'</h3>'}
function loginScreen(){document.getElementById('content').innerHTML=accountCard('Sign in to your company account','Your Gmail account keeps your company data separate')+'<input id="loginApi" class="input" placeholder="HTTPS Backend API URL" value="'+esc(d.settings.cloud?.apiUrl||'')+'"><input id="loginUser" class="input" type="email" placeholder="Gmail address"><input id="loginPass" class="input" type="password" placeholder="Password"><button class="btn green full" onclick="doStartupLogin()">Login & Open App</button><button class="btn light full" onclick="registerScreen()">Create New Company Account</button><div class="muted" style="margin-top:10px;text-align:center">One Gmail = one company account. The same Gmail/password can be used on multiple phones.</div><div id="loginMsg" class="muted" style="margin-top:8px;text-align:center"></div></div></div>'}
function registerScreen(){document.getElementById('content').innerHTML=accountCard('Create company account','Use a Gmail address for your STAR COMMUNICATION account')+'<input id="regApi" class="input" placeholder="HTTPS Backend API URL" value="'+esc(d.settings.cloud?.apiUrl||'')+'"><input id="regCompany" class="input" placeholder="Company / ISP name"><input id="regEmail" class="input" type="email" placeholder="Your Gmail address"><input id="regPass" class="input" type="password" placeholder="Password (minimum 8 characters)"><input id="regPass2" class="input" type="password" placeholder="Confirm password"><button class="btn green full" onclick="doRegister()">Create Account</button><button class="btn light full" onclick="loginScreen()">Back to Login</button><div class="muted" style="margin-top:10px;text-align:center">Customer list, billing, payments, expenses, history and settings belong only to this company account.</div><div id="regMsg" class="muted" style="margin-top:8px;text-align:center"></div></div></div>'}
async function doStartupLogin(){let msg=document.getElementById('loginMsg');try{msg.textContent='Logging in...';let api=document.getElementById('loginApi').value,user=document.getElementById('loginUser').value.trim().toLowerCase(),pass=document.getElementById('loginPass').value;let x=await cloudLogin(api,user,pass);await cloudSync(false);page='dashboard';opts={};render();toast('Login successful')}catch(e){msg.textContent=e.message||'Login failed'}}
async function doRegister(){let msg=document.getElementById('regMsg');try{let api=document.getElementById('regApi').value,email=document.getElementById('regEmail').value.trim().toLowerCase(),company=document.getElementById('regCompany').value.trim(),p=document.getElementById('regPass').value,p2=document.getElementById('regPass2').value;if(p!==p2){msg.textContent='Passwords do not match';return}msg.textContent='Creating account...';let api2=String(api||'').trim().replace(//$/,'');if(!/^https:///i.test(api2))throw new Error('HTTPS API URL required');let rr=await fetch(api2+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password:p,companyName:company})});let x=await rr.json();if(!rr.ok)throw new Error(x.error||'Registration failed');d.settings.cloud={apiUrl:api2,username:email,token:x.token,role:'owner',owner:email,companyName:company};save(false);await cloudSync(false);page='dashboard';opts={};render();toast('Account created successfully')}catch(e){msg.textContent=e.message||'Registration failed'}}
"""
p.write_text(s[:old_start]+new+s[old_end:])
