from pathlib import Path
p=Path("app/src/main/assets/index.html")
s=p.read_text(encoding="utf-8")
D=chr(36)

anchor = "<button class=\\\"small view\\\" onclick=\\\"go('details',{id:" + D + "{c.id}})\\\">Details</button>"
insert = anchor + "<button class=\\\"small view\\\" onclick=\\\"sendOneSms('" + D + "{num}','" + D + "{esc(c.name)}')\\\">📩 SMS</button><button class=\\\"small\\\" style=\\\"background:#7656d6;color:#fff\\\" onclick=\\\"customerPaymentLink('" + D + "{c.id}')\\\">🔗 Payment Link</button>"
if "customerPaymentLink('" + D + "{c.id}')" not in s and anchor in s:
    s=s.replace(anchor,insert,1)

marker="function startup(){"
if "function registerScreen()" not in s:
    block=r'''function accountCard(title,sub){return '<div style="padding:28px 12px 100px"><div class="section" style="padding:22px"><div style="text-align:center"><img src="logo.svg" style="width:70px;height:70px;border-radius:18px"><h1 style="margin:12px 0 3px;color:#0b2145">STAR COMMUNICATION</h1><div class="muted">'+esc(sub)+'</div></div><h3 style="margin-top:22px">'+esc(title)+'</h3>'}
function loginScreen(){document.getElementById('content').innerHTML=accountCard('Company Account Login','Use your Gmail + company password')+'<input id="loginApi" class="input" placeholder="Cloud API URL (HTTPS)" value="'+esc(d.settings.cloud?.apiUrl||'')+'"><input id="loginUser" class="input" type="email" placeholder="Gmail address"><input id="loginPass" class="input" type="password" placeholder="Password"><button class="btn green full" onclick="doStartupLogin()">Login</button><button class="btn light full" style="margin-top:8px" onclick="registerScreen()">Create Company Account</button><div id="loginMsg" class="muted" style="margin-top:10px;text-align:center"></div></div></div>'}
function registerScreen(){document.getElementById('content').innerHTML=accountCard('Create Company Account','Your Gmail owns your company data')+'<input id="regApi" class="input" placeholder="Cloud API URL (HTTPS)" value="'+esc(d.settings.cloud?.apiUrl||'')+'"><input id="regCompany" class="input" placeholder="Company / ISP name"><input id="regEmail" class="input" type="email" placeholder="Gmail address"><input id="regPass" class="input" type="password" placeholder="Password (8+ characters)"><input id="regPass2" class="input" type="password" placeholder="Confirm password"><button class="btn green full" onclick="doRegister()">Create Account</button><button class="btn light full" style="margin-top:8px" onclick="loginScreen()">Back to Login</button><div id="regMsg" class="muted" style="margin-top:10px;text-align:center"></div></div></div>'}
async function doStartupLogin(){let m=document.getElementById('loginMsg');try{let api=document.getElementById('loginApi').value.trim().replace(/\/$/,'');let u=document.getElementById('loginUser').value.trim().toLowerCase();let p=document.getElementById('loginPass').value;m.textContent='Logging in...';let x=await cloudLogin(api,u,p);d.settings.cloud=Object.assign({},d.settings.cloud,{apiUrl:api,username:u,token:x.token,role:x.role||'owner',owner:x.owner||u,companyName:x.companyName||''});save(false);await cloudSync(false);page='dashboard';opts={};render();toast('Login successful')}catch(e){m.textContent=e.message||'Login failed'}}
async function doRegister(){let m=document.getElementById('regMsg');try{let api=document.getElementById('regApi').value.trim().replace(/\/$/,'');let company=document.getElementById('regCompany').value.trim();let u=document.getElementById('regEmail').value.trim().toLowerCase();let p=document.getElementById('regPass').value;let p2=document.getElementById('regPass2').value;if(!/^https:\/\//i.test(api))throw new Error('Cloud API URL is required');if(!/^[^\s@]+@gmail\.com$/i.test(u))throw new Error('Use a valid Gmail address');if(company.length<2)throw new Error('Company name is required');if(p.length<8)throw new Error('Password must be at least 8 characters');if(p!==p2)throw new Error('Passwords do not match');m.textContent='Creating account...';let r=await fetch(api+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:u,password:p,companyName:company})});let x=await r.json();if(!r.ok)throw new Error(x.error||'Registration failed');d.settings.cloud={apiUrl:api,username:u,token:x.token,role:'owner',owner:u,companyName:company};save(false);page='dashboard';opts={};await cloudSync(false);render();toast('Company account created')}catch(e){m.textContent=e.message||'Registration failed'}}
function sendOneSms(phone,name){window.__starSmsPhone=String(phone||'');openSheet('<h3>Send SMS</h3><div class="muted">To: '+esc(name||'Customer')+' • '+esc(phone)+'</div><textarea id="onesms" class="input" rows="6" placeholder="Write your own message"></textarea><button class="btn green full" onclick="doSendOneSms()">Send SMS</button>')}
function doSendOneSms(){let el=document.getElementById('onesms'),msg=el?String(el.value||'').trim():'',phone=String(window.__starSmsPhone||'').trim();if(!phone){toast('Customer phone number missing');return}if(!msg){toast('Write a message first');if(el)el.focus();return}try{if(window.AndroidBridge&&typeof AndroidBridge.sendSms==='function'){let ok=AndroidBridge.sendSms(phone,msg);if(ok){closeSheet();return}}}catch(e){}try{if(window.AndroidBridge&&typeof AndroidBridge.openSmsComposer==='function'&&AndroidBridge.openSmsComposer(phone,msg)){closeSheet();return}}catch(e){}try{window.location.href='smsto:'+encodeURIComponent(phone)+'?body='+encodeURIComponent(msg)}catch(e){toast('SMS app could not be opened')}}
function customerPaymentLink(id){let c=d.customers.find(x=>String(x.id)===String(id));if(!c){toast('Customer not found');return}let base='https://rezaulfahim806-sys.github.io/STAR-COMMUNICATION95/pay.html';let q=new URLSearchParams({code:String(c.id||''),name:String(c.name||''),location:String(c.address||''),package:String(c.pkg||''),bill:String(c.fee||0),prev:String(c.prevDue||0),total:String(due(c)),merchant:String(d.settings.merchantNumber||'01897-099850')});let link=base+'?'+q.toString();window.__starPay={link:link,phone:String(c.phone||''),name:String(c.name||'Customer')};openSheet('<h3>Payment Link</h3><div class="muted">'+esc(c.id)+' • '+esc(c.name)+'</div><textarea id="paylink" class="input" rows="4" readonly>'+esc(link)+'</textarea><button class="btn full" onclick="copyCustomerPaymentLink()">📋 Copy Link</button><button class="btn dark full" style="margin-top:7px" onclick="sendPaymentLinkSms()">✉️ Send SMS</button><button class="btn light full" style="margin-top:7px" onclick="openPaymentPage()">🌐 Open Payment Page</button>')}
async function copyCustomerPaymentLink(){let x=window.__starPay?.link||'';if(!x){toast('Payment link not found');return}try{if(window.AndroidBridge&&typeof AndroidBridge.copyText==='function'){AndroidBridge.copyText(x);toast('Payment link copied');return}if(navigator.clipboard&&navigator.clipboard.writeText){await navigator.clipboard.writeText(x);toast('Payment link copied');return}let t=document.getElementById('paylink');t.focus();t.select();t.setSelectionRange(0,t.value.length);let ok=document.execCommand('copy');toast(ok?'Payment link copied':'Select and copy the link manually')}catch(e){toast('Copy failed — long press the link to copy')}}
function openPaymentPage(){let x=window.__starPay?.link;if(x){if(window.AndroidBridge&&typeof AndroidBridge.openExternalUrl==='function'){AndroidBridge.openExternalUrl(x)}else{location.href=x}}}
function sendPaymentLinkSms(){let x=window.__starPay;if(!x){toast('Payment link not found');return}let msg='Your bill payment link: '+x.link;if(!window.AndroidBridge||typeof AndroidBridge.sendSms!=='function'){toast('SMS service unavailable');return}try{let ok=AndroidBridge.sendSms(x.phone,msg);if(ok){closeSheet();toast('Payment link SMS sent');return}}catch(e){}try{if(AndroidBridge.openSmsComposer&&AndroidBridge.openSmsComposer(x.phone,msg)){closeSheet();toast('SMS composer opened');return}}catch(e){}toast('SMS failed: SMS app could not be opened')}
'''
    if marker in s:
        s=s.replace(marker,block+marker,1)

p.write_text(s,encoding="utf-8")
print("OK")
