from pathlib import Path

html = Path('app/src/main/assets/index.html')
s = html.read_text(encoding='utf-8')

# Final customer SMS/tools patch. Keep Payment -> Send SMS and Payment Link SMS.
script = r'''<script>
(function(){
function cs(){return window.d&&Array.isArray(d.customers)?d.customers:[];}
function fc(id){var x=String(id==null?'':id);return cs().find(function(c){return String(c.id)===x||String(c.clientCode||'')===x;});}
function sms(c,m){if(!c||!c.phone){toast('Customer mobile number নেই');return false;}try{if(window.AndroidBridge&&AndroidBridge.openSmsComposer){AndroidBridge.openSmsComposer(String(c.phone).trim(),m);return true;}location.href='smsto:'+encodeURIComponent(String(c.phone).trim())+'?body='+encodeURIComponent(m);return true;}catch(e){toast('SMS app could not be opened');return false;}}
window.starCustomerSms=function(id){var c=fc(id);if(!c){toast('Customer not found');return;}openSheet('<h3>📩 Send SMS</h3><div class="muted">To: '+esc(c.name||'Customer')+' • '+esc(c.phone||'')+'</div><textarea id="starSmsMsg" class="input" rows="6" placeholder="Write message"></textarea><button class="btn dark full" onclick="starOneSms(\''+String(c.id).replace(/'/g,'')+'\')">📨 Send SMS</button>');};
window.starOneSms=function(id){var c=fc(id),e=document.getElementById('starSmsMsg'),m=e?e.value.trim():'';if(!c){toast('Customer not found');return;}if(!m){toast('Write a message first');return;}if(sms(c,m))closeSheet();};
function list(){var f=(window.opts&&opts.filter)||'all';return cs().filter(function(c){if(f==='expired')return c.status==='expired';if(f==='active')return c.status==='active';if(f==='inactive')return c.status==='inactive';if(f==='unpaid')return typeof due==='function'?due(c)>0:true;if(f==='paid')return typeof paid==='function'?paid(c)>0:false;return true;});}
window.starFilterSms=function(){var a=list().filter(function(c){return c.phone;});if(!a.length){toast('এই তালিকায় mobile number নেই');return;}var f=(window.opts&&opts.filter)||'all',n={all:'All Customers',paid:'Paid Customers',unpaid:'Unpaid Customers',expired:'Expired Customers',active:'Active Customers',inactive:'Inactive Customers'}[f]||'Customers';openSheet('<h3>📩 Send Message — '+n+'</h3><div class="muted">Recipients: '+a.length+'</div><textarea id="starBulkMsg" class="input" rows="6" placeholder="Write message"></textarea><button class="btn dark full" onclick="starSendFilteredSms()">📨 Send to '+n+'</button>');};
window.starSendFilteredSms=function(){var e=document.getElementById('starBulkMsg'),m=e?e.value.trim():'';if(!m){toast('Write a message first');return;}var a=list().filter(function(c){return c.phone;});closeSheet();var i=0;function nx(){if(i>=a.length){toast('SMS finished: '+a.length);return;}sms(a[i++],m);setTimeout(nx,450);}nx();};
window.starCustomerTools=function(){openSheet('<h3>👥 Customer Tools</h3><button class="btn dark full" onclick="starFilterSms()">💬 Send Message</button><button class="btn green full" style="margin-top:7px" onclick="starAllPaymentLinkSms()">🔗 Send Payment Link SMS</button><button class="btn light full" style="margin-top:7px" onclick="exportCustomersCSV()">📊 Download Customer CSV</button><button class="btn light full" style="margin-top:7px" onclick="exportCustomersPDF()">📄 Download Customer PDF</button>');};
function add(a,c){if(!a||a.querySelector('[data-star-sms]'))return;var b=document.createElement('button');b.className='small view';b.textContent='📩 SMS';b.setAttribute('data-star-sms','1');b.onclick=function(){starCustomerSms(c.id);};a.appendChild(b);}
function enhance(){if(typeof page==='undefined')return;if(page==='customers'){var content=document.getElementById('content');if(content&&!document.getElementById('starCustomerToolbar')){var b=document.createElement('div');b.className='section';b.id='starCustomerToolbar';var f=(window.opts&&opts.filter)||'all',n={all:'All Customers',paid:'Paid Customers',unpaid:'Unpaid Customers',expired:'Expired Customers',active:'Active Customers',inactive:'Inactive Customers'}[f]||'Customers';b.innerHTML='<h3>👥 '+n+' Tools</h3><div class="row"><button class="btn dark" onclick="starFilterSms()">📩 Send SMS</button><button class="btn light" onclick="starCustomerTools()">⚙️ More</button></div>';content.insertBefore(b,content.firstChild);}document.querySelectorAll('.customer').forEach(function(card){var a=card.querySelector('.actions'),code=(card.textContent.match(/SC\d+/)||[])[0],c=code?cs().find(function(x){return String(x.clientCode||'')===code;}):null;if(a&&c)add(a,c);});}if(page==='details'){var c=fc(window.opts&&opts.id),a=document.querySelector('.actions');if(c&&a)add(a,c);}var sh=document.getElementById('sheet');if(sh&&document.getElementById('modal')&&document.getElementById('modal').classList.contains('show')){var t=sh.textContent||'',c=fc(window.opts&&opts.id)||fc(window.__starPaymentCustomerId);if(c&&/হিসাব|Payment/i.test(t)&&!sh.querySelector('[data-star-payment-sms]')){var b=document.createElement('button');b.className='btn dark full';b.style.marginTop='7px';b.textContent='📩 Send SMS';b.setAttribute('data-star-payment-sms','1');b.onclick=function(){starCustomerSms(c.id);};sh.appendChild(b);}}}
var og=window.go;if(og&&!window.__starGoWrapped){window.__starGoWrapped=true;window.go=function(p,o,push){og(p,o,push);setTimeout(enhance,80);};}
var oo=window.openSheet;if(oo&&!window.__starOpenWrapped){window.__starOpenWrapped=true;window.openSheet=function(h){oo(h);setTimeout(enhance,30);};}
setInterval(enhance,700);
})();
</script>
'''
if 'window.__starCustomerSmsFinal' not in s:
    script = script.replace('<script>', '<script>window.__starCustomerSmsFinal=true;', 1)
    s = s.replace('</body>', script + '</body>', 1)

html.write_text(s, encoding='utf-8')

java = Path('app/src/main/java/com/starcommunication/isp/MainActivity.java')
j = java.read_text(encoding='utf-8')
if 'saveTextFile(String fileName' not in j:
    anchor = '        @JavascriptInterface public void scheduleExpiry(String phone,String name,String expiry){AutoMessageReceiver.scheduleExpiry(MainActivity.this,phone,name,expiry);}'
    methods = r'''        @JavascriptInterface public void saveTextFile(String fileName,String content,String mime){try{if(Build.VERSION.SDK_INT>=29){android.content.ContentValues v=new android.content.ContentValues();v.put(android.provider.MediaStore.Downloads.DISPLAY_NAME,fileName);v.put(android.provider.MediaStore.Downloads.MIME_TYPE,mime==null?"text/plain":mime);v.put(android.provider.MediaStore.Downloads.RELATIVE_PATH,"Download/STAR COMMUNICATION");android.net.Uri u=getContentResolver().insert(android.provider.MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(u!=null){java.io.OutputStream os=getContentResolver().openOutputStream(u);os.write((content==null?"":content).getBytes(java.nio.charset.StandardCharsets.UTF_8));os.close();runOnUiThread(()->Toast.makeText(MainActivity.this,"CSV saved in Downloads/STAR COMMUNICATION",Toast.LENGTH_LONG).show());}}}catch(Exception e){runOnUiThread(()->Toast.makeText(MainActivity.this,"CSV save failed",Toast.LENGTH_LONG).show());}}
        @JavascriptInterface public void saveCustomerPdf(String fileName,String text){try{android.graphics.pdf.PdfDocument pdf=new android.graphics.pdf.PdfDocument();android.graphics.Paint p=new android.graphics.Paint();p.setColor(android.graphics.Color.BLACK);p.setTextSize(10f);String[] lines=(text==null?"":text).split("\\n",-1);android.graphics.pdf.PdfDocument.Page pg=null;android.graphics.Canvas canvas=null;int no=1,y=35;for(String line:lines){if(pg==null||y>800){if(pg!=null)pdf.finishPage(pg);pg=pdf.startPage(new android.graphics.pdf.PdfDocument.PageInfo.Builder(595,842,no++).create());canvas=pg.getCanvas();y=35;}canvas.drawText(line.length()>88?line.substring(0,88):line,28,y,p);y+=15;}if(pg!=null)pdf.finishPage(pg);if(Build.VERSION.SDK_INT>=29){android.content.ContentValues v=new android.content.ContentValues();v.put(android.provider.MediaStore.Downloads.DISPLAY_NAME,fileName);v.put(android.provider.MediaStore.Downloads.MIME_TYPE,"application/pdf");v.put(android.provider.MediaStore.Downloads.RELATIVE_PATH,"Download/STAR COMMUNICATION");android.net.Uri u=getContentResolver().insert(android.provider.MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(u!=null){java.io.OutputStream os=getContentResolver().openOutputStream(u);pdf.writeTo(os);os.close();runOnUiThread(()->Toast.makeText(MainActivity.this,"PDF saved in Downloads/STAR COMMUNICATION",Toast.LENGTH_LONG).show());}}pdf.close();}catch(Exception e){runOnUiThread(()->Toast.makeText(MainActivity.this,"PDF save failed",Toast.LENGTH_LONG).show());}}
'''
    if anchor not in j:
        raise SystemExit('scheduleExpiry anchor not found')
    j = j.replace(anchor, methods + anchor, 1)
    java.write_text(j, encoding='utf-8')

print('Final customer SMS/list/payment tools patch applied')