from pathlib import Path

html = Path('app/src/main/assets/index.html')
s = html.read_text(encoding='utf-8')

script = r'''<script>
(function(){
  function customers(){return window.d&&Array.isArray(d.customers)?d.customers:[];}
  function phone(c){return String(c&&(c.phone||c.mobile||c.mobileNumber||c.contact||c.msisdn)||'').trim();}
  function findCustomer(id){var x=String(id==null?'':id);return customers().find(function(c){return String(c.id)===x||String(c.clientCode||'')===x;});}
  function money2(n){try{return money(Number(n)||0)}catch(e){return '৳'+(Number(n)||0)}}
  function sendSms(c,msg){var p=phone(c);if(!p){toast('Customer mobile number নেই');return false;}try{if(window.AndroidBridge&&AndroidBridge.openSmsComposer){AndroidBridge.openSmsComposer(p,msg);return true;}}catch(e){}try{location.href='smsto:'+encodeURIComponent(p)+'?body='+encodeURIComponent(msg);return true}catch(e){toast('SMS app could not be opened');return false;}}
  function currentList(){var f=(window.opts&&opts.filter)||'all';return customers().filter(function(c){if(f==='expired')return String(c.status||'').toLowerCase()==='expired';if(f==='active')return String(c.status||'').toLowerCase()==='active';if(f==='inactive')return String(c.status||'').toLowerCase()==='inactive';if(f==='unpaid')return typeof due==='function'?Number(due(c))>0:Number(c.runningBill||c.monthlyFee||0)>0;if(f==='paid')return typeof paid==='function'?Number(paid(c))>0:false;return true;});}
  window.starCustomerSms=function(id){var c=findCustomer(id);if(!c){toast('Customer not found');return;}openSheet('<h3>📩 Send SMS</h3><div class="muted">To: '+esc(c.name||'Customer')+' • '+esc(phone(c)||'No mobile')+'</div><textarea id="starSmsMsg" class="input" rows="6" placeholder="Write message"></textarea><button class="btn dark full" onclick="starOneSms(\''+String(c.id).replace(/'/g,'')+'\')">📨 Send SMS</button>');};
  window.starOneSms=function(id){var c=findCustomer(id),e=document.getElementById('starSmsMsg'),m=e?e.value.trim():'';if(!c){toast('Customer not found');return;}if(!m){toast('Write a message first');return;}if(sendSms(c,m))closeSheet();};
  window.starFilterSms=function(){var a=currentList().filter(function(c){return phone(c);});if(!a.length){toast('এই তালিকায় mobile number নেই');return;}var f=(window.opts&&opts.filter)||'all',n={all:'All Customers',paid:'Paid Customers',unpaid:'Unpaid Customers',expired:'Expired Customers',active:'Active Customers',inactive:'Inactive Customers'}[f]||'Customers';openSheet('<h3>📩 Send Message — '+n+'</h3><div class="muted">Recipients: '+a.length+'</div><textarea id="starBulkMsg" class="input" rows="6" placeholder="Write message"></textarea><button class="btn dark full" onclick="starSendFilteredSms()">📨 Send to '+n+'</button>');};
  window.starSendFilteredSms=function(){var e=document.getElementById('starBulkMsg'),m=e?e.value.trim():'';if(!m){toast('Write a message first');return;}var a=currentList().filter(function(c){return phone(c);});closeSheet();var i=0;function next(){if(i>=a.length){toast('SMS finished: '+a.length);return;}sendSms(a[i++],m);setTimeout(next,650);}next();};
  function paymentLink(c){var code=String(c.clientCode||c.id||'');var q=new URLSearchParams();q.set('code',code);q.set('name',String(c.name||'Customer'));q.set('location',String(c.address||c.location||''));q.set('package',String(c.pkg||c.packageName||''));q.set('bill',String(Number(c.fee||c.monthlyFee||0)));q.set('prev',String(Number(c.prevDue||c.previousDue||0)));q.set('total',String(typeof due==='function'?due(c):Number(c.prevDue||c.previousDue||0)+Number(c.fee||c.monthlyFee||0)));q.set('merchant',String((d.settings&&d.settings.merchantNumber)||'01897-099850'));return 'https://rezaulfahim806-sys.github.io/STAR-COMMUNICATION95/pay.html?'+q.toString();}
  window.starAllPaymentLinkSms=function(){var a=currentList().filter(function(c){return phone(c);});if(!a.length){toast('এই তালিকায় mobile number নেই');return;}var f=(window.opts&&opts.filter)||'all',n={all:'All Customers',paid:'Paid Customers',unpaid:'Unpaid Customers',expired:'Expired Customers',active:'Active Customers',inactive:'Inactive Customers'}[f]||'Customers';openSheet('<h3>🔗 Payment Link SMS — '+n+'</h3><div class="muted">Each customer gets their own link • Recipients: '+a.length+'</div><textarea id="starPayBulkMsg" class="input" rows="6">STAR COMMUNICATION\nDear {name},\nClient Code: {code}\nTotal Due: {total}\nPayment Link: {link}</textarea><button class="btn green full" onclick="starSendPaymentLinks()">📨 Send Payment Link SMS</button>');};
  window.starSendPaymentLinks=function(){var e=document.getElementById('starPayBulkMsg'),tpl=e?e.value.trim():'';if(!tpl){toast('Write a message first');return;}var a=currentList().filter(function(c){return phone(c);});closeSheet();var i=0;function next(){if(i>=a.length){toast('Payment Link SMS finished: '+a.length);return;}var c=a[i++],tot=typeof due==='function'?due(c):Number(c.prevDue||c.previousDue||0)+Number(c.fee||c.monthlyFee||0),m=tpl.replaceAll('{name}',String(c.name||'Customer')).replaceAll('{code}',String(c.clientCode||c.id||'')).replaceAll('{total}',money2(tot)).replaceAll('{link}',paymentLink(c));sendSms(c,m);setTimeout(next,650);}next();};
  window.starCustomerTools=function(){openSheet('<h3>👥 Customer Tools</h3><button class="btn dark full" onclick="starFilterSms()">💬 Send Message</button><button class="btn green full" style="margin-top:7px" onclick="starAllPaymentLinkSms()">🔗 Send Payment Link SMS</button><button class="btn light full" style="margin-top:7px" onclick="exportCustomersCSV()">📊 Download Customer CSV</button><button class="btn light full" style="margin-top:7px" onclick="exportCustomersPDF()">📄 Download Customer PDF</button>');};
  window.exportCustomersCSV=function(){var rows=[['Client Code','Name','Mobile','Address','Package','Monthly','Previous Due','Running Bill','Total Due','Status']];customers().forEach(function(c){var tot=typeof due==='function'?due(c):Number(c.prevDue||c.previousDue||0)+Number(c.fee||c.monthlyFee||0);rows.push([c.clientCode||c.id||'',c.name||'',phone(c),c.address||c.location||'',c.pkg||c.packageName||'',c.fee||c.monthlyFee||0,c.prevDue||c.previousDue||0,c.runningBill||0,tot,c.status||'']);});var csv=rows.map(function(r){return r.map(function(v){return '"'+String(v==null?'':v).replace(/"/g,'""')+'"';}).join(',');}).join('\n');if(window.AndroidBridge&&AndroidBridge.saveTextFile){AndroidBridge.saveTextFile('STAR-COMMUNICATION-Customers.csv',csv,'text/csv');toast('CSV saved in Downloads');}else{var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='STAR-COMMUNICATION-Customers.csv';a.click();toast('CSV download started');}};
  window.exportCustomersPDF=function(){var lines=['STAR COMMUNICATION — CUSTOMER LIST','Generated: '+new Date().toLocaleString(),''];customers().forEach(function(c){var tot=typeof due==='function'?due(c):Number(c.prevDue||c.previousDue||0)+Number(c.fee||c.monthlyFee||0);lines.push('Client Code: '+(c.clientCode||c.id||''));lines.push('Name: '+(c.name||''));lines.push('Mobile: '+phone(c));lines.push('Address: '+(c.address||c.location||''));lines.push('Package: '+(c.pkg||c.packageName||''));lines.push('Monthly: '+money2(c.fee||c.monthlyFee||0)+' | Previous Due: '+money2(c.prevDue||c.previousDue||0)+' | Total Due: '+money2(tot));lines.push('Status: '+(c.status||''));lines.push('----------------------------------------');});var text=lines.join('\n');if(window.AndroidBridge&&AndroidBridge.saveCustomerPdf){AndroidBridge.saveCustomerPdf('STAR-COMMUNICATION-Customers.pdf',text);toast('PDF saved in Downloads');}else{toast('PDF export needs Android app');}};
  function addSms(card,c){if(!card||!c||card.querySelector('[data-star-sms]'))return;var a=card.querySelector('.actions');if(!a)return;var b=document.createElement('button');b.className='small view';b.textContent='📩 SMS';b.setAttribute('data-star-sms','1');b.onclick=function(){starCustomerSms(c.id);};a.appendChild(b);}
  function enhance(){if(typeof page==='undefined')return;if(page==='customers'){var content=document.getElementById('content');if(content&&!document.getElementById('starCustomerToolbar')){var b=document.createElement('div');b.className='section';b.id='starCustomerToolbar';var f=(window.opts&&opts.filter)||'all',n={all:'All Customers',paid:'Paid Customers',unpaid:'Unpaid Customers',expired:'Expired Customers',active:'Active Customers',inactive:'Inactive Customers'}[f]||'Customers';b.innerHTML='<h3>👥 '+n+' Tools</h3><div class="row"><button class="btn dark" onclick="starFilterSms()">📩 Send SMS</button><button class="btn light" onclick="starCustomerTools()">⚙️ More</button></div>';content.insertBefore(b,content.firstChild);}document.querySelectorAll('.customer').forEach(function(card){var code=(card.textContent.match(/SC\d+/)||[])[0],c=code?customers().find(function(x){return String(x.clientCode||'')===code;}):null;if(c)addSms(card,c);});}if(page==='details'){var c=findCustomer(window.opts&&opts.id),a=document.querySelector('.actions');if(c&&a)addSms({querySelector:function(){return a;}},c);}}
  var oldGo=window.go;if(oldGo&&!window.__starGoWrapped){window.__starGoWrapped=true;window.go=function(p,o,push){oldGo(p,o,push);setTimeout(enhance,120);};}
  var oldOpen=window.openSheet;if(oldOpen&&!window.__starOpenWrapped){window.__starOpenWrapped=true;window.openSheet=function(h){oldOpen(h);setTimeout(enhance,40);};}
  setInterval(enhance,700);
})();
</script>
'''
if 'window.__starCustomerSmsFinalV2' not in s:
    script = script.replace('<script>', '<script>window.__starCustomerSmsFinalV2=true;', 1)
    s = s.replace('</body>', script + '</body>', 1)
html.write_text(s, encoding='utf-8')

java = Path('app/src/main/java/com/starcommunication/isp/MainActivity.java')
j = java.read_text(encoding='utf-8')
if 'saveTextFile(String fileName' not in j:
    anchor='        @JavascriptInterface public void scheduleExpiry(String phone,String name,String expiry){AutoMessageReceiver.scheduleExpiry(MainActivity.this,phone,name,expiry);}'
    methods='''        @JavascriptInterface public void saveTextFile(String fileName,String content,String mime){try{if(Build.VERSION.SDK_INT>=29){android.content.ContentValues v=new android.content.ContentValues();v.put(android.provider.MediaStore.Downloads.DISPLAY_NAME,fileName);v.put(android.provider.MediaStore.Downloads.MIME_TYPE,mime==null?"text/plain":mime);v.put(android.provider.MediaStore.Downloads.RELATIVE_PATH,"Download/STAR COMMUNICATION");android.net.Uri u=getContentResolver().insert(android.provider.MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(u!=null){java.io.OutputStream os=getContentResolver().openOutputStream(u);os.write((content==null?"":content).getBytes(java.nio.charset.StandardCharsets.UTF_8));os.close();runOnUiThread(()->Toast.makeText(MainActivity.this,"CSV saved in Downloads/STAR COMMUNICATION",Toast.LENGTH_LONG).show());}}}catch(Exception e){runOnUiThread(()->Toast.makeText(MainActivity.this,"CSV save failed",Toast.LENGTH_LONG).show());}}
        @JavascriptInterface public void saveCustomerPdf(String fileName,String text){try{android.graphics.pdf.PdfDocument pdf=new android.graphics.pdf.PdfDocument();android.graphics.Paint p=new android.graphics.Paint();p.setColor(android.graphics.Color.BLACK);p.setTextSize(10f);String[] lines=(text==null?"":text).split("\\\\n",-1);android.graphics.pdf.PdfDocument.Page pg=null;android.graphics.Canvas canvas=null;int no=1,y=35;for(String line:lines){if(pg==null||y>800){if(pg!=null)pdf.finishPage(pg);pg=pdf.startPage(new android.graphics.pdf.PdfDocument.PageInfo.Builder(595,842,no++).create());canvas=pg.getCanvas();y=35;}canvas.drawText(line.length()>88?line.substring(0,88):line,28,y,p);y+=15;}if(pg!=null)pdf.finishPage(pg);if(Build.VERSION.SDK_INT>=29){android.content.ContentValues v=new android.content.ContentValues();v.put(android.provider.MediaStore.Downloads.DISPLAY_NAME,fileName);v.put(android.provider.MediaStore.Downloads.MIME_TYPE,"application/pdf");v.put(android.provider.MediaStore.Downloads.RELATIVE_PATH,"Download/STAR COMMUNICATION");android.net.Uri u=getContentResolver().insert(android.provider.MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(u!=null){java.io.OutputStream os=getContentResolver().openOutputStream(u);pdf.writeTo(os);os.close();runOnUiThread(()->Toast.makeText(MainActivity.this,"PDF saved in Downloads/STAR COMMUNICATION",Toast.LENGTH_LONG).show());}}pdf.close();}catch(Exception e){runOnUiThread(()->Toast.makeText(MainActivity.this,"PDF save failed",Toast.LENGTH_LONG).show());}}
'''
    if anchor not in j: raise SystemExit('scheduleExpiry anchor not found')
    j=j.replace(anchor,methods+anchor,1)
    java.write_text(j,encoding='utf-8')
print('customer SMS, payment-link SMS, CSV and PDF export fixed')