from pathlib import Path
p=Path('app/src/main/assets/index.html')
s=p.read_text(encoding='utf-8')
css='''<style id="starCompactUi">html,body{width:100%;min-height:100%;overflow-x:hidden}body{font-size:13px}.app{max-width:480px;min-height:100svh}.header{height:54px;padding:5px 9px;padding-top:max(5px,env(safe-area-inset-top))}.top{height:42px;gap:5px}.logo{width:32px;height:32px}.icon{width:32px;font-size:21px;padding:0}.brand{font-size:15px}.content{padding:9px 9px calc(76px + env(safe-area-inset-bottom))}.title{font-size:18px}.grid{gap:6px}.stat{min-height:74px;border-radius:12px;padding:9px}.stat .label{font-size:10px}.stat .num{font-size:19px;margin-top:6px}.section,.customer,.chart{border-radius:11px;padding:9px;margin:6px 0}.section h3{font-size:13px}.input,.select{padding:8px;border-radius:8px}.btn{padding:8px 10px}.kpi{padding:6px 0}.moneybox{padding:7px}.moneybox b{font-size:14px}.avatar{width:34px;height:34px}.badge{padding:3px 6px;font-size:8px}.detail{padding:5px 0}.small{padding:6px 7px;font-size:9px}.chartbars{height:95px}.bottom{height:56px;padding-bottom:env(safe-area-inset-bottom)}.bottom button{font-size:8px}.bottom span{font-size:16px}.drawer{width:270px;padding:12px}.menu{margin-top:18px}.menu button{padding:10px 7px}.sheet{max-height:88svh;padding:12px}</style>'''
if 'id="starCompactUi"' not in s:s=s.replace('</head>',css+'</head>',1)
old="function restoreData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x||!Array.isArray(x.customers))throw 0;if(!confirm('Restore this backup? Current data will be replaced by selected backup.'))return;d=x;save();render();toast('Backup restored')}catch(_){toast('Invalid backup')}};r.readAsText(f)}"
new="function restoreData(e){let f=e.target.files&&e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x||typeof x!=='object'||!Array.isArray(x.customers))throw 0;if(!confirm('Restore this backup? Current data will be replaced by selected backup.')){e.target.value='';return}d={customers:Array.isArray(x.customers)?x.customers:[],payments:Array.isArray(x.payments)?x.payments:[],expenses:Array.isArray(x.expenses)?x.expenses:[],pending:Array.isArray(x.pending)?x.pending:[],history:Array.isArray(x.history)?x.history:[],settings:Object.assign({},DEF.settings,x.settings||{})};d.settings.olt=Object.assign({},DEF.settings.olt,(x.settings&&x.settings.olt)||{});save();e.target.value='';fix();render();toast('Backup restored successfully')}catch(_){e.target.value='';toast('Invalid backup file')}};r.readAsText(f)}"
if old not in s:raise SystemExit('restoreData pattern missing')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
print('compact UI and restore patch applied')
