from pathlib import Path
import re

p=Path('app/src/main/assets/index.html')
s=p.read_text(encoding='utf-8')

if '.editbtn{' not in s:
    s=s.replace('.view{background:#edf0f5;color:#334155}', '.view{background:#edf0f5;color:#334155}.editbtn{background:#1677d2;color:#fff}.linkbtn{background:#7656d6;color:#fff}', 1)

card_re=r"function card\(c\)\{.*?\}function customers\(\)"
card=r'''function ensureClientCode(c){if(c.clientCode)return String(c.clientCode);var max=0;(d.customers||[]).forEach(function(x){var m=String(x.clientCode||'').match(/^SC(\d+)$/i);if(m)max=Math.max(max,Number(m[1]));});c.clientCode='SC'+String(max+1).padStart(3,'0');return c.clientCode;}
function ensureAllClientCodes(){var ch=false;(d.customers||[]).forEach(function(c){if(!c.clientCode){ensureClientCode(c);ch=true;}});if(ch)save();}
function paymentLinkFor(c){var q=new URLSearchParams();q.set('code',ensureClientCode(c));q.set('name',String(c.name||'Customer'));q.set('location',String(c.address||c.location||''));q.set('package',String(c.pkg||c.packageName||''));q.set('bill',String(Number(c.fee||c.monthlyFee||0)));q.set('prev',String(Number(c.prevDue||0)));q.set('total',String(typeof due==='function'?due(c):Number(c.prevDue||0)+Number(c.fee||0)));q.set('merchant',String((d.settings&&d.settings.merchantNumber)||'01897-099850'));return 'https://rezaulfahim806-sys.github.io/STAR-COMMUNICATION95/pay.html?'+q.toString();}
function generatePaymentLink(id){var c=d.customers.find(function(x){return String(x.id)===String(id);});if(!c){toast('Customer not found');return;}var link=paymentLinkFor(c);openSheet('<h3>🔗 Payment Link</h3><div class="muted">'+esc(ensureClientCode(c))+' • '+esc(c.name||'')+'</div><input id="customerPayLink" class="input" readonly value="'+esc(link)+'"><button class="btn full" onclick="copyCustomerPaymentLink()">📋 Copy Link</button><button class="btn dark full" style="margin-top:7px" onclick="sendPaymentLinkSMS(\''+String(c.id).replace(/'/g,"\\'")+"\')">📨 Send Msg</button><button class="btn light full" style="margin-top:7px" onclick="window.open(\''+link.replace(/'/g,'%27')+'\',\'_blank\')">🌐 Open Payment Page</button>');}
function copyCustomerPaymentLink(){var e=document.getElementById('customerPayLink');if(!e)return;var ok=function(){toast('Payment link copied');};if(navigator.clipboard)navigator.clipboard.writeText(e.value).then(ok).catch(function(){e.select();document.execCommand('copy');ok();});else{e.select();document.execCommand('copy');ok();}}
function sendPaymentLinkSMS(id){var c=d.customers.find(function(x){return String(x.id)===String(id);});if(!c||!c.phone){toast('Customer mobile number নেই');return;}var link=paymentLinkFor(c),total=typeof due==='function'?due(c):Number(c.prevDue||0)+Number(c.fee||0);var msg='STAR COMMUNICATION\nCustomer: '+(c.name||'Customer')+'\nClient Code: '+ensureClientCode(c)+'\nTotal Due: '+money(total)+'\nPayment Link: '+link;try{if(window.AndroidBridge&&AndroidBridge.sendSms)AndroidBridge.sendSms(String(c.phone),msg);else window.location.href='sms:'+String(c.phone)+'?body='+encodeURIComponent(msg);toast('Payment link message sent');}catch(e){toast('Message failed');}}
function card(c){ensureClientCode(c);var dv=due(c),pp=paid(c),run=Math.max(0,Number(c.fee||0)-Math.min(Number(c.fee||0),pp)),num=esc(c.phone||'');return `<div class="customer"><div class="cmain"><div class="avatar">${esc((c.name||'?')[0].toUpperCase())}</div><div class="grow"><div class="name">${esc(c.name)}</div><div class="muted">${esc(ensureClientCode(c))} • ${num} • ${esc(c.pkg||'')}</div></div><span class="badge ${c.status}">${String(c.status).toUpperCase()}</span></div><div class="actions">${billBadge(c)}</div><div class="detail"><span>Connection Date</span><b>${esc(c.connectionDate||'—')}</b></div><div class="detail"><span>Expiry Date</span><b>${esc(c.expiry||'—')}</b></div><div class="detail"><span>Monthly Bill</span><b>${money(c.fee)}</b></div><div class="detail"><span>Previous Due</span><b>${money(c.prevDue)}</b></div><div class="detail"><span>Running Bill</span><b>${money(run)}</b></div><div class="detail"><span>Total Due</span><b>${money(dv)}</b></div><div class="actions"><button class="small call" onclick="callCustomer('${num}')">📞 Phone</button><button class="small wa" onclick="waCustomer('${num}')">WhatsApp</button><button class="small view" onclick="go('details',{id:'${c.id}'})">View Customer</button><button class="small linkbtn" onclick="generatePaymentLink('${c.id}')">🔗 Payment Link</button>${dv>0?`<button class="small pay" onclick="payCustomer('${c.id}')">হিসাব / Pay</button>`:''}</div></div>`;}function customers()'''
s,n=re.subn(card_re,card,s,count=1,flags=re.S)
if n!=1: raise SystemExit('card block not found')

details_re=r"function details\(\)\{.*?\}function callCustomer\(n\)"
details=r'''function editCustomer(id){var c=d.customers.find(function(x){return String(x.id)===String(id);});if(!c){toast('Customer not found');return;}ensureClientCode(c);openSheet('<h3>✏️ Edit Customer</h3><label class="muted">Client Code</label><input class="input" value="'+esc(c.clientCode)+'" readonly><input id="ec_name" class="input" placeholder="Customer name" value="'+esc(c.name||'')+'"><input id="ec_phone" class="input" placeholder="Mobile / WhatsApp" value="'+esc(c.phone||'')+'"><input id="ec_address" class="input" placeholder="Address" value="'+esc(c.address||'')+'"><input id="ec_pkg" class="input" placeholder="Package" value="'+esc(c.pkg||'')+'"><input id="ec_fee" class="input" type="number" placeholder="Monthly fee" value="'+Number(c.fee||0)+'"><label class="muted">Connection Date</label><input id="ec_cd" class="input" type="date" value="'+esc(c.connectionDate||today())+'"><label class="muted">Expiry Date</label><input id="ec_ex" class="input" type="date" value="'+esc(c.expiry||'')+'"><input id="ec_prev" class="input" type="number" placeholder="Previous due" value="'+Number(c.prevDue||0)+'"><select id="ec_st" class="select"><option value="active" '+(c.status==='active'?'selected':'')+'>Active</option><option value="inactive" '+(c.status==='inactive'?'selected':'')+'>Inactive</option><option value="expired" '+(c.status==='expired'?'selected':'')+'>Expired</option></select><button class="btn green full" onclick="saveEditedCustomer(\''+String(c.id).replace(/'/g,"\\'")+"\')">Save Changes</button>');}
function saveEditedCustomer(id){var c=d.customers.find(function(x){return String(x.id)===String(id);});if(!c)return;c.name=document.getElementById('ec_name').value.trim();c.phone=document.getElementById('ec_phone').value.trim();c.address=document.getElementById('ec_address').value.trim();c.pkg=document.getElementById('ec_pkg').value.trim();c.fee=Number(document.getElementById('ec_fee').value||0);c.connectionDate=document.getElementById('ec_cd').value||c.connectionDate||today();c.expiry=document.getElementById('ec_ex').value||'';c.prevDue=Number(document.getElementById('ec_prev').value||0);c.status=document.getElementById('ec_st').value||'active';ensureClientCode(c);save();closeSheet();toast('Customer updated');render();}
function details(){var c=d.customers.find(function(x){return String(x.id)===String(opts.id);});if(!c){go('customers');return;}ensureClientCode(c);var hist=d.payments.filter(function(x){return String(x.customer)===String(c.id);}).sort(function(a,b){return String(b.date).localeCompare(String(a.date));});return `<h1 class="title">Customer Details</h1><button class="btn light" onclick="appBack()">← Back</button><div class="customer"><div class="cmain"><div class="avatar">${esc((c.name||'?')[0].toUpperCase())}</div><div class="grow"><div class="name">${esc(c.name)}</div><div class="muted">${esc(ensureClientCode(c))} • ${esc(c.phone||'')}</div></div><span class="badge ${c.status}">${String(c.status).toUpperCase()}</span></div><div class="detail"><span>Client Code</span><b>${esc(ensureClientCode(c))}</b></div><div class="detail"><span>Connection Date</span><b>${esc(c.connectionDate||'—')}</b></div><div class="detail"><span>Expiry Date</span><b>${esc(c.expiry||'—')}</b></div><div class="detail"><span>Address</span><b>${esc(c.address||'—')}</b></div><div class="detail"><span>Package</span><b>${esc(c.pkg||'—')}</b></div><div class="detail"><span>Monthly</span><b>${money(c.fee)}</b></div><div class="detail"><span>Previous Due</span><b>${money(c.prevDue)}</b></div><div class="detail"><span>Running Bill</span><b>${money(billDue(c))}</b></div><div class="detail"><span>Total Due</span><b>${money(due(c))}</b></div><div class="actions"><button class="small editbtn" onclick="editCustomer('${c.id}')">✏️ Edit Customer</button><button class="small call" onclick="callCustomer('${esc(c.phone||'')}')">📞 Phone</button><button class="small wa" onclick="waCustomer('${esc(c.phone||'')}')">WhatsApp</button><button class="small linkbtn" onclick="generatePaymentLink('${c.id}')">🔗 Payment Link</button><button class="small pay" onclick="payCustomer('${c.id}')">💳 হিসাব / Payment</button></div></div><div class="section"><h3>Payment History</h3>${hist.length?hist.map(function(x){return `<div class="detail"><span>${esc(x.date)} • ${esc(x.month||'')} • ${esc(x.source||'manual')}</span><b>${money(x.amount)}</b></div>`}).join(''):'<div class="muted">No payments yet.</div>'}</div>`;}function callCustomer(n)'''
s,n=re.subn(details_re,details,s,count=1,flags=re.S)
if n!=1: raise SystemExit('details block not found')

if 'ensureAllClientCodes();render();</script>' not in s:
    s=s.replace('render();</script></body></html>','ensureAllClientCodes();render();</script></body></html>',1)

p.write_text(s,encoding='utf-8')
print('customer actions patched')
