from pathlib import Path
p=Path('app/src/main/assets/index.html')
s=p.read_text(encoding='utf-8')
marker="function paymentLink(c){"
if marker not in s:
    raise SystemExit('paymentLink function not found')
portal="""function customerPortal(){try{let q=new URLSearchParams(location.search);let code=String(q.get('pay')||'').trim();if(!code)return false;let c=(d.customers||[]).find(x=>String(x.clientCode||'').trim()===code);if(!c){document.getElementById('content').innerHTML='<section class=section><h2>STAR COMMUNICATION</h2><p>Customer not found.</p></section>';return true}let merchant=String(q.get('merchant')||d.settings.merchantNumber||'01897-099850').trim();let pppoe=String(c.pppoeUsername||c.username||'');let pass=String(c.pppoePassword||c.password||'');let total=typeof due==='function'?due(c):Number(c.prevDue||0)+Number(c.fee||0);let paymsg='STAR COMMUNICATION Bill Payment\\nClient Code: '+String(c.clientCode||c.id)+'\\nAmount: '+String(total);document.getElementById('content').innerHTML='<section class=section style=\"text-align:center;padding:20px\"><img src=\"logo.svg\" style=\"width:82px;height:82px;border-radius:18px\"><h1 style=\"margin:8px 0 2px\">STAR COMMUNICATION</h1><div class=muted>Customer Bill Payment</div></section><section class=section><div class=detail><span>Customer</span><b>'+esc(c.name||'Customer')+'</b></div><div class=detail><span>Client Code</span><b>'+esc(c.clientCode||c.id)+'</b></div><div class=detail><span>Username</span><b>'+esc(pppoe)+'</b></div><div class=detail><span>Password</span><b>'+esc(pass)+'</b></div><div class=detail><span>Previous Due</span><b>'+money(c.prevDue||0)+'</b></div><div class=detail><span>Current Bill</span><b>'+money(c.fee||0)+'</b></div><div class=detail><span>Total Due</span><b style=\"font-size:20px;color:#c62828\">'+money(total)+'</b></div></section><section class=section><h3>💳 Pay with bKash</h3><div class=detail><span>bKash Merchant Number</span><b>'+esc(merchant)+'</b></div><p class=muted>Send your bill amount to the merchant number above using bKash. Use your Client Code as the reference.</p><button class=btn green full onclick=\"navigator.clipboard&&navigator.clipboard.writeText('"+merchant+"').then(()=>toast('Merchant number copied'))\">Copy Merchant Number</button><button class=btn dark full style=\"margin-top:7px\" onclick=\"navigator.clipboard&&navigator.clipboard.writeText('"+paymsg+"').then(()=>toast('Payment details copied'))\">Copy Payment Details</button><p class=muted style=\"margin-top:10px\">After payment, keep the bKash Transaction ID and contact STAR COMMUNICATION if needed.</p></section>';return true}catch(e){return false}}\n"""
s=s.replace(marker,portal+marker,1)
old="render();</script>"
new="try{if(!customerPortal())render();}catch(e){render();}</script>"
if old in s:s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
print('customer-specific payment portal added')
