from pathlib import Path
p=Path("app/src/main/assets/index.html")
s=p.read_text()
if "function registerScreen()" not in s:
    marker="function startup(){"
    block=r'''function accountCard(title,sub){return '<div style="padding:26px 16px 100px"><div class="section" style="margin-top:25px;padding:22px"><div style="text-align:center"><img src="logo.svg" style="width:72px;height:72px;border-radius:18px"><h1 style="margin:12px 0 3px;color:#0b2145">STAR COMMUNICATION</h1><div class="muted">'+esc(sub)+'</div></div><h3 style="margin-top:22px">'+esc(title)+'</h3>'}
function loginScreen(){document.getElementById('content').innerHTML=accountCard('Company Account Login','Login with your Gmail account')+'<input id="loginApi" class="input" placeholder="HTTPS Backend API URL" value="'+esc(d.settings.cloud?.apiUrl||'')+'"><input id="loginUser" class="input" type="email" placeholder="Gmail address"><input id="loginPass" class="input" type="password" placeholder="Password"><button class="btn green full" onclick="doStartupLogin()">Login & Open App</button><button class="btn light full" style="margin-top:7px" onclick="registerScreen()">Create New Company Account</button><div class="muted" style="margin-top:10px;text-align:center">Same Gmail + password works on another phone. Different Gmail = separate company data.</div><div id="loginMsg" class="muted" style="margin-top:8px;text-align:center"></div></div></div>'}
function registerScreen(){document.getElementById('content').innerHTML=accountCard('Create Company Account','One Gmail account owns one company dataset')+'<input id="regApi" class="input" placeholder="HTTPS Backend API URL" value="'+esc(d.settings.cloud?.apiUrl||'')+'"><input id="regCompany" class="input" placeholder="Company / ISP name"><input id="regEmail" class="input" type="email" placeholder="Gmail address"><input id="regPass" class="input" type="password" placeholder="Password (minimum 8 characters)"><input id="regPass2" class="input" type="password" placeholder="Confirm password"><button class="btn green full" onclick="doRegister()">Create Account</button><button class="btn light full" style="margin-top:7px" onclick="loginScreen()">Back to Login</button><div id="regMsg" class="muted" style="margin-top:8px;text-align:center"></div></div></div>'}
async function doStartupLogin(){let msg=document.getElementById('loginMsg');try{msg.textContent='Logging in...';let api=document.getElementById('loginApi').value,user=document.getElementById('loginUser').value.trim().toLowerCase(),pass=document.getElementById('loginPass').value;let x=await cloudLogin(api,user,pass);d.settings.cloud.role=x.role||'owner';d.settings.cloud.owner=x.owner||user;d.settings.cloud.companyName=x.companyName||'';await cloudSync(false);page='dashboard';opts={};render();toast('Login successful')}catch(e){msg.textContent=e.message||'Login failed'}}
async function doRegister(){let msg=document.getElementById('regMsg');try{let api=String(document.getElementById('regApi').value||'').trim().replace(/\/$/,''),email=String(document.getElementById('regEmail').value||'').trim().toLowerCase(),company=String(document.getElementById('regCompany').value||'').trim(),p=document.getElementById('regPass').value,p2=document.getElementById('regPass2').value;if(!/^https:\/\//i.test(api))throw new Error('HTTPS API URL required');if(!/^[^\s@]+@gmail\.com$/i.test(email))throw new Error('Use a valid Gmail address');if(p.length<8)throw new Error('Password must be at least 8 characters');if(p!==p2)throw new Error('Passwords do not match');msg.textContent='Creating account...';let rr=await fetch(api+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:email,password:p,companyName:company})});let x=await rr.json();if(!rr.ok)throw new Error(x.error||'Registration failed');d.settings.cloud={apiUrl:api,username:email,token:x.token,role:x.role||'owner',owner:x.owner||email,companyName:x.companyName||company};save(false);await cloudSync(false);page='dashboard';opts={};render();toast('Company account created')}catch(e){msg.textContent=e.message||'Registration failed'}}
function messageCenter(){openSheet('<h3>SMS Message Center</h3><textarea id="smsmsg" class="input" rows="5" placeholder="Write SMS message"></textarea><button class="btn dark full" onclick="sendBulkSms(\'all\')">Send to All</button><button class="btn green full" style="margin-top:7px" onclick="sendBulkSms(\'unpaid\')">Send to Unpaid</button><button class="btn red full" style="margin-top:7px" onclick="sendBulkSms(\'expired\')">Send to Expired</button><div class="muted" style="margin-top:8px">Direct SIM SMS uses your phone SIM. Allow SMS permission when Android asks.</div></div>')}
function sendBulkSms(mode){let msg=document.getElementById('smsmsg')?.value||'';if(!msg.trim()){toast('Write a message first');return}let rows=[];(d.customers||[]).forEach(c=>{let st=String(c.status||'').toLowerCase(),ok=mode==='all'||(mode==='unpaid'&&due(c)>0)||(mode==='expired'&&st==='expired');if(ok&&c.phone)rows.push(String(c.phone)+'|'+String(c.name||'Customer'))});if(!rows.length){toast('No matching customers');return}if(!window.AndroidBridge||typeof AndroidBridge.sendBulk!=='function'){toast('SMS service unavailable');return}AndroidBridge.sendBulk(rows.join('\n'),msg);closeSheet()}
'''
    if marker not in s: raise SystemExit("startup marker missing")
    s=s.replace(marker,block+marker,1)
s=s.replace("if(!r.ok)throw new Error('Login failed');\n let x=await r.json();if(!x.token)throw new Error('No login token');","let x=await r.json();if(!r.ok)throw new Error(x.error||'Login failed');if(!x.token)throw new Error(x.error||'No login token');")
s=s.replace('<button onclick="openSettings()">⚙️ Settings</button>','<button onclick="messageCenter();closeDrawer()">💬 SMS Message Center</button><button onclick="openSettings()">⚙️ Settings</button><button onclick="cloudLogout()">🔐 Account Logout</button>')
p.write_text(s)
